#!/bin/bash

DIRECTORY="$(cd $(dirname $0); pwd)"

ln -sf "${DIRECTORY}/zshrc" ~/.zshrc
ln -sf "${DIRECTORY}/tmux.conf" ~/.tmux.conf
ln -sf "${DIRECTORY}/vimrc" ~/.vimrc
ln -sf "${DIRECTORY}/gitconfig" ~/.gitconfig

# if [ ${SPIN} ]; then
#
# fi
